# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krynncal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndate',
            name='current_date',
        ),
        migrations.AddField(
            model_name='campaigndate',
            name='date_str',
            field=models.CharField(default='351-09-13 00:00:00', max_length=20),
            preserve_default=False,
        ),
    ]
