# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-01 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0013_urlconfrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'character statuses',
            },
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('guest_name', models.CharField(default=b'Stranger', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='JournalAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kind', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shlog.CharacterStatus')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtext', models.CharField(blank=True, default=b'', max_length=42)),
                ('context', models.CharField(blank=True, default=b"Ship's Log: The Allegiance", max_length=128)),
                ('journal_date', models.CharField(default=b'4715/MM/DD', max_length=10)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlog.JournalAuthor')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
            },
        ),
        migrations.CreateModel(
            name='JournalSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_section', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SectionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='journalsection',
            name='section_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlog.SectionGroup'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlog.JournalSection'),
        ),
    ]
