# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
