# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shlog', '0002_associatedcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiongroup',
            name='for_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shlog.AssociatedCampaign'),
        ),
    ]
