# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehedgepart',
            name='parent_cardinality',
            field=models.IntegerField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], default=0),
        ),
    ]
