# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehtest', '0003_ehtile_explorer_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehexplorer',
            name='default_size',
            field=models.PositiveIntegerField(default=32),
        ),
    ]
