# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehtest', '0004_ehexplorer_default_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehexplorer',
            name='orientation_offset',
            field=models.IntegerField(default=0),
        ),
    ]
