# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonPlayerCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(max_length=255, upload_to=b'')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
            },
        ),
    ]
